server:
  port: 8090

logging:
  level:
     root: INFO
     com.cibertec.gateway: DEBUG


spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: IJIpukMxjpw72kacPwWmbpJsZ4VZKrOL
